### ISSUE TITLE
Provides an unique provider of type: memory throws NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by M3lkior** [gravitee-io/gravitee-management-rest-api#32]
Hi,

Here is my gravitee.yml configuration for authentication providers : 

```
security:
  type: basic                       # authentication type
  providers:                        # required authentication providers
    - type: memory
      users:
        - user:
          username: user
          password: password
          roles: USER               # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
        - user:
          username: admin
          password: admin
          roles: ADMIN   
```

This configuration throws NoSuchBeanDefinitionException when i try to start the management-api : 

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.Collection io.gravitee.management.service.impl.IdentityServiceImpl.identityManagers; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [io.gravitee.management.providers.core.identity.IdentityManager] found for dependency [collection of io.gravitee.management.providers.core.identity.IdentityManager]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1210)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at io.gravitee.management.standalone.Container.initializeContext(Container.java:95)
	at io.gravitee.management.standalone.Container.initialize(Container.java:53)
	at io.gravitee.management.standalone.Container.<init>(Container.java:43)
	at io.gravitee.management.standalone.Container.main(Container.java:134)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.Collection io.gravitee.management.service.impl.IdentityServiceImpl.identityManagers; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [io.gravitee.management.providers.core.identity.IdentityManager] found for dependency [collection of io.gravitee.management.providers.core.identity.IdentityManager]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 14 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [io.gravitee.management.providers.core.identity.IdentityManager] found for dependency [collection of io.gravitee.management.providers.core.identity.IdentityManager]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1301)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:999)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 16 more
```

**Comment by brasseld** [comment]
Resolved in 0.13.x
